## IMAGE DOWNLOAD SETTINGS

# Bounding box (caja delimitadora) para buscar panoramas.
# Puedes obtener estas coordenadas haciendo clic derecho en Google Maps.
# Sub-área 3 (Fila 1, Col 3)
top_left: [6.369212, -75.586281]
bottom_right: [6.254542000000001, -75.550747]

# Cuántos puntos de prueba se buscan en la cuadrícula.
# Un número más bajo es más rápido, pero puede omitir algunos panoramas.
resolution: 100

## IMAGE PROJECTION SETTINGS

# Resolution of the projected image. e.g. resolution of 1024 will give 1024x1024 image
projected_resolution: 1024
# Which sides to keep for the panoramas
sides:
  front: true
  back: true
  left: true
  right: true